import Image from "next/image";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisScroll from "./components/Functions/LenisScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden antialiased flex flex-col min-h-screen`}
      >
        <div className="">{children}</div>
        <footer className="w-full py-5 bg-foreground z-9999">
          TESTING
           <Image 
            src="/logo1.svg"
            alt="Logo"
            width={32}
            height={32}
            className="w-8 h-8 scale-75 object-contain"
        />
        </footer>
      </body>
      <LenisScroll />
    </html>
  );
}
